name: "Flavor compatibility setup file"
stages:
  # For all alpine based flavors
  boot.before:
    - if: |
        [[ $(kairos-agent state get system.os.vendor | tr -d '\n') =~ "^alpine" ]]
      commands:
      - mount -o mode=1777,nosuid,nodev -t tmpfs tmpfs /tmp
      - mount --make-rshared /
  # opensuse ARM RPI
  # As currently we don't support yet LVM with ARM, we drop OEM by default and be optional.
  rootfs.after:
    - if: |
       [ ! -f "/run/cos/recovery_mode" ] && \
       [[ $(kairos-agent state get system.os.vendor | tr -d '\n') =~ "^opensuse" ]] && [[ $(kairos-agent state get system.os.vendor | tr -d '\n') =~ 'rpi$'' ]]
      name: "Layout configuration"
      environment_file: /run/cos/cos-layout.env
      environment:
        VOLUMES: "LABEL=COS_PERSISTENT:/usr/local"
        OVERLAY: "tmpfs:25%"
        RW_PATHS: "/var /etc /srv"
        PERSISTENT_STATE_PATHS: >-
          /etc/systemd
          /etc/rancher
          /etc/sysconfig
          /etc/runlevels
          /etc/ssh
          /etc/iscsi
          /etc/cni
          /home
          /opt
          /root
          /usr/libexec
          /var/log
          /var/lib/rancher
          /var/lib/kubelet
          /var/lib/wicked
          /var/lib/longhorn
          /var/lib/cni
        PERSISTENT_STATE_BIND: "true"
    - if: |
        [ ! -f /run/cos/recovery_mode ] && [ ! -f /run/cos/live_mode ] && \
        [[ $(kairos-agent state get system.os.vendor | tr -d '\n') =~ 'rpi$'' ]]
      name: "Grow persistent partition by default on RPI flavors"
      layout:
        device:
          label: COS_PERSISTENT
        expand_partition:
          # Size 0 is required to specify all remaining space
          size: 0
  # ubuntu only
  initramfs.after:
    - name: "setupcon initramfs.after"
      - if: |
          [[ $(kairos-agent state get system.os.vendor | tr -d '\n') =~ "^ubuntu" ]]
      commands:
        - echo "Run setupcon to have fonts working on Ubuntu"
        - setupcon
